services:
  postgres:
    image: postgres:16-alpine@sha256:57c72fd2a128e416c7fcc499958864df5301e940bca0a56f58fddf30ffc07777
    container_name: trackflow-postgres
    environment:
      POSTGRES_USER: trackflow
      POSTGRES_PASSWORD: trackflow
      POSTGRES_DB: trackflow
    ports:
      - '5432:5432'
    volumes:
      - trackflow_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U trackflow']
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine@sha256:6ab0b6e7381779332f97b8ca76193e45b0756f38d4c0dcda72dbb3c32061ab99
    container_name: trackflow-redis
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  trackflow_pgdata:
